name: Monthly Model Retraining

# Trigger: runs automatically on the 1st of every month at 02:00 UTC and can also be started manually
on:
  schedule:
    - cron: '0 2 1 * *'
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t fraud-detectio-mlops:latest .

      - name: Run retraining container for 15 minutes
        run: |
          echo "Starting container..."
          docker run --rm \
            -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -e AWS_DEFAULT_REGION="${{ secrets.AWS_DEFAULT_REGION }}" \
            -e BUCKET_NAME="${{ secrets.BUCKET_NAME }}" \
            -e MLFLOW_TRACKING_URI="${{ secrets.MLFLOW_TRACKING_URI }}" \
            -v ${{ github.workspace }}/mlruns:/app/mlruns \
            fraud-detectio-mlops:latest &

          CONTAINER_PID=$!
          echo "Container running — waiting 15 minutes (900 seconds)..."
          sleep 900
          echo "Stopping container..."
          kill $CONTAINER_PID || true

      - name: Verify MLflow logs
        run: |
          echo "Contents of mlruns directory after retraining:"
          ls -R ${{ github.workspace }}/mlruns || echo "No mlruns folder found"
